### ISSUE TITLE
UX: Confusing "Save" button when voting

### ISSUE THREAD

**Issue by W3D3** [GustavAT/Votor#3]
Just save on selection-change and move the button for finishing to the bottom, so users are not tempted to press it when not all options have been filled out.

![inkedvotor cywl at_vote_a7fb025d-1c1d-4a30-9f0b-08d659088b0f_li](https://user-images.githubusercontent.com/1103924/49392289-4bf98480-f72e-11e8-9416-5070b27782c8.jpg)

**Comment by GustavAT** [comment]
Our dev-team already discussed this issue:

- ~~The _Abschliessen_ button will stay in the top card.~~
- ~~The save button will be removed from every card and instead placed in the top card (next to _Abschliessen_).~~

- The _Complete_ button is moved to the bottom to ensure that the user has seen all questions before finishing a vote.
- The current selections are saved if clicking on _Complete_ and the user gets feedback if not all questions were voted for.
- A vote is finally complete if all questions are voted for.
- The _Save_ button will finally be removed.

**Comment by GustavAT** [comment]
Fixed with e1a1159b66316fef724bcf5fd13c6c42e7932f5d
