### ISSUE TITLE
Printing QR codes

### ISSUE THREAD

**Issue by Xifiggam** [GustavAT/Votor#6]
Upon printing the QR codes with the standard windows print ot pdf I only receive a one side pdf with cut qr codes.
[sfsdfs.pdf](https://github.com/GustavAT/Votor/files/2652612/sfsdfs.pdf)

**Comment by Monomus** [comment]
Problem caused by browser default printing margin. Fixed by setting the margin to a fixed value on all browsers.

**Comment by Xifiggam** [comment]
Problem is still persisting

[nsdfnsofnsio.pdf](https://github.com/GustavAT/Votor/files/2662356/nsdfnsofnsio.pdf)
