### ISSUE TITLE
Editing Active Events - Reactivating an Event to active status

### ISSUE THREAD

**Issue by Xifiggam** [GustavAT/Votor#8]
In case of human failure, it'd be great to be able to add/edit/delete existing categories/nominees/weights ... during and active event.

If the user makes a mistake during creation of the event it cannot be fixed later.

Additionally it'd be great to reactivate a finished event in case of premature closing/changes afterwards. Right now the user would need to create a new event/have everyone vote anew/hand out new QR codes for this.

**Comment by Monomus** [comment]
Reactivating finished Events will be implemented.

Editing categories and nominees of an existing events can be achieved by resetting the event.
Adding tokens to an active event will be implemented.

**Comment by GustavAT** [comment]
Fixed in e1c82397618fed48f1b3c4610a59aa9f58f3556b
