### ISSUE TITLE
IMPORTANT: Mark category as Overall Winner

### ISSUE THREAD

**Issue by W3D3** [GustavAT/Votor#9]
Instead of adding all the sums to the Overall winner, the chosen category (currently named question) should be used instead.
This is important for the GameJam.

**Comment by GustavAT** [comment]
Hiding an overall winner in the results-page was implemented with fa2a9dba04cfb9518273e070f022f601930e35cb (see image below).

![image](https://user-images.githubusercontent.com/6452952/49657442-fb409f00-fa3f-11e8-967c-3ba386a1d4a2.png)
